### ISSUE TITLE
Configure cannot detect build/host/target on Windows

### ISSUE THREAD

**Issue by lsorber** [coin-or/Cbc#190]
Using the MSYS2 toolchain, `configure` (specifically, `config.guess`) cannot detect the build/host/target on Windows. A workaround is to manually specify `--build=x86_64-w64-mingw32`.

Related to #5 in the sense that using a more recent version of Autotools will probably fix the problem.

**Comment by lsorber** [comment]
Is the issue resolved?

**Comment by svigerske** [comment]
There is work in progress that will resolve this, but progress is slow. There is nothing we will do particularly for Cbc before the upgrade of the autotools will happen.

**Comment by lsorber** [comment]
What would the best place for this issue be, if not the Cbc repository? Since it is not resolved yet, I think it should at least be tracked somewhere.

**Comment by svigerske** [comment]
This should be in coin-or-tools/BuildTools. But the issue is resolved in BuildTools/master. It's just that Cbc cannot use BuildTools/master yet, as BuildTools/master is still in development / not usable yet.

**Comment by lsorber** [comment]
If I understand it well, that means this issue _for Cbc in particular_ is not resolved yet then?

**Comment by svigerske** [comment]
One could say that it is resolved in the autotools-update branch.

I don't see the point of this discussion. The issue has been acknowledged. As we said, we are working on fixing this. There are branches or similar where this is already fixed. It is not going to be forgotten.

**Comment by lsorber** [comment]
I don't imagine it will be forgotten, but if the issue is already closed, how will we know when it is resolved?

**Comment by svigerske** [comment]
There will be a huge announcement. With fireworks and everything.

**Comment by lsorber** [comment]
If you say so :-)
